### ISSUE TITLE
Issue: Migrating database does not honor the configuration file

### ISSUE THREAD

**Issue by 3v1n0** [ubuntu/authd#807]
### Is there an existing issue for this?

- [x] I have searched the existing issues and found none that matched mine

### Describe the issue

If authd is running with a configuration file that points to a database location, it will still try to migrate the `consts.OldDBDir` position hardcoded to `/var/cache/authd/`, while if one had a configuration file such as:

```yaml
verbosity: 2
paths:
  cache: /tmp/authd-cache
  database: /tmp/authd-db
  socket: /tmp/authd.sock
```

that's not honored:

```
2025/02/22 04:05:28 ERROR can't migrate database directory from "/var/cache/authd/" to "/tmp/authd-db": rename /var/cache/authd/ /tmp/authd-db: permission denied
```

### Double check your logs

- [x] I have redacted any sensitive information from the logs
